// DO NOT EDIT — This file is generated by kysely-codegen.
// Run `npm run generate-types` to regenerate.
// Placeholder until first migration is run against a live database.

export interface Database {
  users: UsersTable;
  sessions: SessionsTable;
  session_participants: SessionParticipantsTable;
  media_captures: MediaCapturesTable;
  karaoke_catalog: KaraokeCatalogTable;
}

export interface UsersTable {
  id: string;
  firebase_uid: string | null;
  display_name: string;
  avatar_url: string | null;
  created_at: Date;
}

export interface SessionsTable {
  id: string;
  host_user_id: string;
  party_code: string;
  status: string;
  dj_state: unknown | null;
  event_stream: unknown | null;
  vibe: string | null;
  venue_name: string | null;
  created_at: Date;
  ended_at: Date | null;
}

export interface SessionParticipantsTable {
  id: string;
  session_id: string;
  user_id: string | null;
  guest_name: string | null;
  participation_score: number;
  top_award: string | null;
  feedback_score: number | null;
  joined_at: Date;
}

export interface MediaCapturesTable {
  id: string;
  session_id: string;
  user_id: string | null;
  storage_path: string;
  trigger_type: string;
  dj_state_at_capture: unknown | null;
  created_at: Date;
}

export interface KaraokeCatalogTable {
  id: string;
  song_title: string;
  artist: string;
  youtube_video_id: string;
  channel: string | null;
  is_classic: boolean;
  created_at: Date;
  updated_at: Date;
}
