export enum DJStateType {
  LOBBY = 'LOBBY',
  ICEBREAKER = 'ICEBREAKER',
  SONG_ACTIVE = 'SONG_ACTIVE',
  SONG_OVER = 'SONG_OVER',
  BRIDGE = 'BRIDGE',
  CEREMONY_VOTING = 'CEREMONY_VOTING',
  CEREMONY_SILENCE = 'CEREMONY_SILENCE',
  CEREMONY_REVEAL = 'CEREMONY_REVEAL',
  GROUP_SING = 'GROUP_SING',
  FINALE = 'FINALE',
}
